baseurl = "http://hpc.tafreshu.ac.ir/docs"
publishdir = "docs"
languageCode = "fa-IR"
title = "کلاستر دوامی"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true

# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Amir H. Firouzian"
	description = "Tafresh HPC Doc Page"
	copyright = "Released under the GPLv3+ license"

	version = "۰.۱"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "green"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	email   = ""

[[menu.main]]
	name   = "روضه"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "شروع به کار"
	url    = "شروع-به-کار/"
	weight = 10

[[menu.main]]
	name   = "جابجایی فایل"
	url    = "جابجایی-فایل/"
	weight = 20

[[menu.main]]
	name   = "قوانین"
	url    = "قوانین/"
	weight = 30

[[menu.main]]
	name   = "چشم‌انداز"
	url    = "چشم-انداز/"
	weight = 40


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
